### ISSUE TITLE
write method not work

### ISSUE THREAD

**Issue by springeye** [flymzero/webdav_client#30]
call write is error
**code is :**
```
    var map = box.toMap();
    client.write("backup-${DateTime.now().millisecondsSinceEpoch}",
        Uint8List.fromList(jsonEncode(map).codeUnits));dart
```

**error is :**
```bash
[🔔 Dio] _MultiStream<List<int>> cannot be used to imply a default content-type, please set a proper content-type in the request.
         #0      ImplyContentTypeInterceptor.onRequest (package:dio/src/interceptors/imply_content_type.dart:45:36)
         #1      DioMixin.fetch.requestInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:409:26)
         #2      new Future.<anonymous closure> (dart:async/future.dart:256:37)
         #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
         #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
         #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
         #6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

**Comment by mostcute** [comment]
` client.write("syncdata.json", Uint8List.fromList(jsonString.codeUnits));`
sameproblem
```
[🔔 Dio] _MultiStream<List<int>> cannot be used to imply a default content-type, please set a proper content-type in the request.
         #0      ImplyContentTypeInterceptor.onRequest (package:dio/src/interceptors/imply_content_type.dart:45:36)
         #1      DioMixin.fetch.requestInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:409:26)
         #2      new Future.<anonymous closure> (dart:async/future.dart:256:37)
         #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
         #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
         #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
         #6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

**Comment by szuwest** [comment]
> ` client.write("syncdata.json", Uint8List.fromList(jsonString.codeUnits));` sameproblem
> 
> ```
> [🔔 Dio] _MultiStream<List<int>> cannot be used to imply a default content-type, please set a proper content-type in the request.
>          #0      ImplyContentTypeInterceptor.onRequest (package:dio/src/interceptors/imply_content_type.dart:45:36)
>          #1      DioMixin.fetch.requestInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:409:26)
>          #2      new Future.<anonymous closure> (dart:async/future.dart:256:37)
>          #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
>          #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
>          #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
>          #6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
> ```

has the same problem

**Comment by seth-shi** [comment]
client.setHeaders({
      'accept-charset': 'utf-8',
      'content-type': 'application/octet-stream'
    });
