### ISSUE TITLE
FormatException: Invalid date format

### ISSUE THREAD

**Issue by cwj214228** [flymzero/webdav_client#51]
Unhandled exception:
FormatException: Invalid date format
Tue, 08 Oct 2024 14:45:01 GMT
#0      DateTime.parse (dart:core/date_time.dart:351:7)
#1      WebdavXml.toFiles.<anonymous closure> (package:webdav_client/src/xml.dart:87:28)
#2      List.forEach (dart:core-patch/growable_array.dart:417:8)
#3      WebdavXml.toFiles (package:webdav_client/src/xml.dart:36:10)
#4      Client.readProps (package:webdav_client/src/client.dart:82:22)

**Comment by cwj214228** [comment]
DateTime.parse("Tue, 08 Oct 2024 14:45:01 GMT");

**Comment by cwj214228** [comment]
```dart
            // create time
            final cTimeElements = findElements(prop, 'creationdate');
            DateTime? cTime = cTimeElements.isNotEmpty
                ? str2LocalTime(cTimeElements.single.text)
                : null;
```

**Comment by 2265290305** [comment]
where is the core/date_time.dart and where to write this code:[[final cTimeElements = findElements(prop, 'creationdate');
            DateTime? cTime = cTimeElements.isNotEmpty
                ? str2LocalTime(cTimeElements.single.text)
                : null; ]]?
